### ISSUE TITLE
Regression in Spartan6 bitstreams

### ISSUE THREAD

**Issue by vzapolskiy** [jordens/bscan_spi_bitstreams#2]
Hi @jordens 

I believe there is a regression introduced in your latest update c790432aca5 (I've tested that the state of bitstreams at 5a487dbe768 is fine).

I checked bitstreams ```bscan_spi_xc6slx45.bit``` (csg324) and ```bscan_spi_xc6slx9t.bit``` (qg144), and now I get the following error with OpenOCD:

```
> jtagspi_init 0 bscan_spi_bitstreams/bscan_spi_xc6slx45.bit
loaded file bscan_spi_bitstreams/bscan_spi_xc6slx45.bit to pld device 0 in 3s 748575us
JTAG tap: xc6s.tap tap/device found: 0x34008093 (mfg: 0x049 (Xilinx), part: 0x4008, ver: 0x3)
Unknown flash device (ID 0x00ffffff)
```

If I revert the last commit, then SPI flash is detected and reprogrammed as expected:
```
> jtagspi_init 0 bscan_spi_bitstreams/bscan_spi_xc6slx45.bit
loaded file bscan_spi_bitstreams/bscan_spi_xc6slx45.bit to pld device 0 in 3s 763310us
JTAG tap: xc6s.tap tap/device found: 0x34008093 (mfg: 0x049 (Xilinx), part: 0x4008, ver: 0x3)
Found flash device 'micron n25q128' (ID 0x0018ba20)
flash 'jtagspi' found at 0x00000000
```

On my boards there is no other SPI devices on the bus.

Could you please check if you see the same issue?

Thank you!

**Comment by jordens** [comment]
The bitstreams here in master are synchronized with [new openocd changes](https://github.com/m-labs/openocd). 
The old or release openocd versions need to use the [single-tap](https://github.com/jordens/bscan_spi_bitstreams/commits/single-tap) branch.

**Comment by vzapolskiy** [comment]
@jordens 

> The old or release openocd versions need to use the single-tap branch.

Thank you for information.
